
# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Scouting-Site

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  FLUTTER_VERSION: 3.22.0

jobs:
  formatting-analysis:
    name: "Check Formatting & Analyze"
    runs-on: ubuntu-latest

    steps:
        - name: Checkout repo
        uses: actions/checkout@v4

        - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
            flutter-version: ${{ env.FLUTTER_VERSION }}
            cache: true
            cache-path: ${{ runner.tool_cache }}/flutter/linux

        - name: Install dependencies
        run: flutter pub get

        - name: Generate mocks
        run: dart run build_runner build

        - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed lib/* test/*

        - name: Analyze project source
        run: flutter analyze --no-fatal-infos --no-fatal-warnings
        
  test:
    name: "Run Tests"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true
          cache-path: ${{ runner.tool_cache }}/flutter/linux

      - name: Install dependencies
        run: flutter pub get

      - name: Generate mocks
        run: dart run build_runner build

      - name: Run tests
        run: flutter test --coverage

   build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            build-option: "linux"
            artifact-path: "build/linux/x64/release/bundle"
            artifact-name: Elastic-Linux
            executable-type: portable
    name: "Build - Web"
    needs: [formatting-analysis, test]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install flutter dependencies
        if: ${{ matrix.build-option == 'linux' }}
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true
          cache-path: ${{ runner.tool_cache }}/flutter/${{ matrix.build-option }}

      - name: Install dependencies
        run: flutter pub get

      - name: Generate icons
        run: dart run flutter_launcher_icons

      - name: Build app
        run: flutter build web --web-renderer html --release 