name: Flutter CI and Deploy to GitHub Pages

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set up Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install dependencies
        run: flutter pub get

      # Uncomment this step to verify the use of 'flutter format' on each commit.
      # - name: Verify formatting
      #   run: flutter format --set-exit-if-changed .

      - name: Analyze project source
        run: flutter analyze

      - name: Run tests
        run: flutter test

      # Build the Flutter web project
      - name: Build Flutter Web
        run: flutter build web --release

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add -f build/web
          git commit -m "Deploy to GitHub Pages"
          git push origin `git subtree split --prefix build/web master`:gh-pages --force
