name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the master branch
      uses: actions/checkout@v3
      with:
        ref: master 

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: "3.24.1"

    - name: Install dependencies
      run: flutter pub get

    - name: Build Flutter web release
      run: flutter build web --release

    - name: Deploy to GitHub Pages
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git clone --branch=ghpages https://github.com/${{ github.repository }}.git ghpages
        rsync -av --delete build/web/ ghpages/
        cd ghpages
        git add --all
        git commit -m "Deploy from master branch via GitHub Actions"
        git push --force origin ghpages
